name: Deploy to Naver Cloud Platform

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to NCR
      uses: docker/login-action@v3
      with:
        registry: timer.kr.ncr.ntruss.com
        username: ${{ secrets.NCR_USERNAME }}
        password: ${{ secrets.NCR_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: timer.kr.ncr.ntruss.com/malan-timer-ai:1.0.0
        cache-from: type=gha
        cache-to: type=gha,mode=max